import { Product } from "@/components/product-card"

export const productsData: Product[] = [

  // ─── FUNGICIDAS ────────────────────────────────────────────────────────────
  {
    id: "1",
    name: "Baktillis",
    slug: "baktillis",
    presentation: "Suspensión concentrada 1L",
    type: "Suspensión concentrada",
    description: "Fungicida biológico a base de Bacillus subtilis para control de hongos y bacterias fitopatógenas.",
    fullDescription: "Baktillis es un fungicida microbiológico formulado con Bacillus subtilis de alta concentración (6-C). Su acción multisitio permite el control efectivo de enfermedades causadas por hongos y bacterias en diversos cultivos. Actúa por competencia, antibiosis y activación de las defensas naturales de la planta.",
    benefits: ["Control de hongos y bacterias", "Acción preventiva y curativa", "Compatible con manejo integrado", "Sin periodo de carencia"],
    application: "Aplicar de forma preventiva o a los primeros síntomas. Dosis: 1-2 L/ha en aspersión foliar o drench.",
    category: "FUNGICIDAS",
    image: "/images/products/baktillis.png",
  },
  {
    id: "2",
    name: "NatuControl",
    slug: "natucontrol",
    presentation: "Polvo humectable 400g",
    type: "Polvo humectable",
    description: "Fungicida biológico a base de Trichoderma harzianum para control de patógenos del suelo.",
    fullDescription: "NatuControl es un fungicida biológico a base de Trichoderma harzianum, un hongo benéfico que parasita y controla hongos patógenos del suelo como Rhizoctonia, Fusarium y Pythium. Ideal para protección radicular en cultivos de alto valor.",
    benefits: ["Control de hongos del suelo", "Mejora el sistema radicular", "Seguro para cultivos orgánicos", "Efecto prolongado"],
    application: "Aplicar al suelo al momento del trasplante o durante el desarrollo del cultivo. Dosis: 400g-800g/ha.",
    category: "FUNGICIDAS",
    image: "/images/products/natucontrol-new.png",
  },
  {
    id: "3",
    name: "Alteza",
    slug: "alteza",
    presentation: "Polvo humectable 500g",
    type: "Polvo humectable — Inoculante",
    description: "Inoculante bioprotector radicular con consorcio de microorganismos benéficos para cultivos de alto valor.",
    fullDescription: "Alteza es un inoculante de bioprotección radicular que combina Bacillus subtilis, Trichoderma asperellum y Pseudomonas fluorescens. Protege las raíces de patógenos y estimula el crecimiento. Contiene además Molibdeno y Ácido Indolacético para mayor vigor.",
    benefits: ["Bioprotección radicular", "Triple acción microbiana", "Estimulación del crecimiento", "Certificado para uso orgánico"],
    application: "Aplicar en semilla o al trasplante. Dosis: 500g por hectárea o 2-4 g/L en tratamiento de semilla.",
    category: "FUNGICIDAS",
    image: "/images/products/alteza.png",
  },
  {
    id: "4",
    name: "Nemagyne",
    slug: "nemagyne",
    presentation: "Concentrado emulsionable 1L",
    type: "Concentrado emulsionable — Coadyuvante",
    description: "Coadyuvante nematicida con biopolímeros y extractos botánicos bioactivados para control de nematodos.",
    fullDescription: "Nemagyne es un coadyuvante especializado formulado con extractos botánicos bioactivados y biopolímeros de aminopolisacáridos. Actúa como potenciador del control de nematodos y mejora la acción de nematicidas biológicos. Reduce la movilidad y penetración de nematodos en raíces.",
    benefits: ["Control complementario de nematodos", "Biopolímeros naturales", "Compatible con otros biológicos", "Sin residuos"],
    application: "Aplicar al suelo en drench o fertirriego. Dosis: 1-2 L/ha. Puede mezclar con otros nematicidas.",
    category: "FUNGICIDAS",
    image: "/images/products/nemagyne.png",
  },
  {
    id: "5",
    name: "Nemakron",
    slug: "nemakron",
    presentation: "Polvo humectable 1kg",
    type: "Polvo humectable — Fungicida nematicida",
    description: "Fungicida nematicida biológico con consorcio de hongos entomopatógenos para control de nematodos.",
    fullDescription: "Nemakron es un nematicida biológico que combina Pochonia chlamydosporia, Paecilomyces lilacinus, extracto de yuca y quitina. Este consorcio parasita huevos y hembras de nematodos fitoparásitos, reduciendo significativamente las poblaciones en el suelo.",
    benefits: ["Control de nematodos del suelo", "Múltiples modos de acción", "Mejora estructura del suelo", "Apto para agricultura orgánica"],
    application: "Incorporar al suelo antes de siembra o trasplante. Dosis: 1-2 kg/ha.",
    category: "FUNGICIDAS",
    image: "/images/products/nemakron.png",
  },
  {
    id: "6",
    name: "Bac Ilia",
    slug: "bac-ilia",
    presentation: "Suspensión concentrada 1L",
    type: "Suspensión concentrada — Fungicida microbiológico",
    description: "Fungicida microbiológico a base de Bacillus subtilis para protección preventiva y curativa.",
    fullDescription: "Bac Ilia es un fungicida biológico desarrollado con Bacillus subtilis de alta pureza. Su formulación en suspensión concentrada garantiza máxima cobertura foliar y del suelo. Protege contra mildiu, tizón tardío, botrytis y otras enfermedades fúngicas.",
    benefits: ["Bacillus subtilis de alta pureza", "Acción preventiva y curativa", "OMRI Listed — uso orgánico", "Compatible con bioestimulantes"],
    application: "Aplicar foliarmente cada 7-10 días en modo preventivo. Dosis: 2-4 mL/L o 2-4 L/ha.",
    category: "FUNGICIDAS",
    image: "/images/products/bac-ilia.png",
  },

  // ─── BIOINSECTICIDAS ───────────────────────────────────────────────────────
  {
    id: "7",
    name: "Aba Krone",
    slug: "aba-krone",
    presentation: "Concentrado emulsionable 1L",
    type: "Concentrado emulsionable — Insecticida",
    description: "Insecticida a base de Abamectina para control de ácaros, trips, minadores y nematodos.",
    fullDescription: "Aba Krone es un insecticida concentrado emulsionable a base de Abamectina 1.8%. Actúa por contacto e ingestión afectando el sistema nervioso de insectos y ácaros. Efectivo contra araña roja, trips, minadores de hoja y mosquita blanca en una amplia gama de cultivos.",
    benefits: ["Amplio espectro de acción", "Control de ácaros y trips", "Acción por contacto e ingestión", "Rápida acción"],
    application: "Aplicar al detectar la plaga. Dosis: 0.5-1 L/ha. Respetar intervalo de 7 días entre aplicaciones.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/abakrone.png",
  },
  {
    id: "8",
    name: "Ajick",
    slug: "ajick",
    presentation: "Solución acuosa 1L",
    type: "Solución acuosa — Repelente botánico",
    description: "Repelente botánico a base de extracto de ajo (Allium sativum) para manejo integrado de plagas.",
    fullDescription: "Ajick es un repelente botánico formulado con extracto esencial de ajo al 87%. Sus compuestos azufrados actúan como repelente de insectos y ácaros, siendo una herramienta efectiva en programas de manejo integrado. OMRI Listed y apto para agricultura orgánica.",
    benefits: ["Repelente natural de amplio espectro", "Sin toxicidad para humanos", "Compatible con enemigos naturales", "OMRI Listed"],
    application: "Aplicar preventivamente o al detectar primeras plagas. Dosis: 1-2 L/ha cada 5-7 días.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/ajick-new.png",
  },
  {
    id: "9",
    name: "AK-Neem",
    slug: "ak-neem",
    presentation: "Concentrado emulsionable 1L",
    type: "Concentrado emulsionable — Insecticida",
    description: "Insecticida botánico con Alicina y Capsaicina para control de insectos chupadores y masticadores.",
    fullDescription: "AK-Neem combina extracto de ajo (Alicina 67.0%) y Capsaicina (3.5%) en un concentrado emulsionable de amplio espectro. Su doble modo de acción repelente y de contacto controla eficazmente moscas blancas, pulgones, trips y ácaros. Apto para uso en agricultura orgánica.",
    benefits: ["Doble modo de acción", "Alicina + Capsaicina", "Control de moscas blancas y pulgones", "Sin periodo de carencia"],
    application: "Aplicar al detectar la plaga. Dosis: 1-2 L/ha. Repetir cada 7-10 días según presión de plaga.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/ak-neem.png",
  },
  {
    id: "10",
    name: "Azaním",
    slug: "azanim",
    presentation: "Concentrado emulsionable 1L",
    type: "Concentrado emulsionable — Insecticida",
    description: "Insecticida botánico a base de Azadiractina 3% para control de plagas de insectos chupadores y masticadores.",
    fullDescription: "Azaním es un insecticida botánico de alta pureza a base de Azadiractina al 3%. Controla eficazmente moscas blancas, pulgones, trips, minadores, orugas y otras plagas mediante su acción antialimentaria, reguladora del crecimiento y ovicida. Sin resistencias conocidas.",
    benefits: ["Azadiractina al 3%", "Control de múltiples plagas", "Acción ovicida", "Bajo impacto ambiental"],
    application: "Aplicar en aspersión total cubriendo bien el follaje. Dosis: 0.5-1 L/ha.",
    category: "BIOINSECTICIDAS",
    image: "/images/products/azanim-new.png",
  },

  // ─── BIOFORTIFICANTES ──────────────────────────────────────────────────────
  {
    id: "11",
    name: "Glumix",
    slug: "glumix",
    presentation: "Polvo inoculante 1kg",
    type: "Polvo — Inoculante micorrízico",
    description: "Inoculante a base de hongos endomicorrízicos (VAM) para mejorar absorción de agua y nutrientes.",
    fullDescription: "Glumix es un inoculante micorrízico que contiene esporas de hongos endomicorrízicos VAM (20,000 esporas viables/kg). Establece simbiosis con las raíces ampliando significativamente su área de absorción, mejorando la captación de fósforo, agua y micronutrientes. Premio Nacional de Tecnología e Innovación.",
    benefits: ["20,000 esporas viables/kg", "Mayor absorción de fósforo y agua", "Resistencia al estrés hídrico", "Premio Nacional de Innovación"],
    application: "Incorporar al suelo antes de siembra o trasplante. Dosis: 1-2 kg/ha o aplicar en surco.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/glumix-new.png",
  },
  {
    id: "12",
    name: "Glumix Irrigation",
    slug: "glumix-irrigation",
    presentation: "Sólido granulado 1kg",
    type: "Sólido — Inoculante bioactivador",
    description: "Bioactivador radicular con micorrizas, ácidos húmicos y fúlvicos para fertirriego y aplicación al suelo.",
    fullDescription: "Glumix Irrigation es un bioactivador formulado para aplicación vía fertirriego. Combina esporas de hongos endomicorrízicos (20%), ácidos húmicos y fúlvicos (20%), extracto de Ascophyllum nodosum (8%), extracto de yuca (5%) y ácido indolacético. Premio Nacional de Innovación e Innovagro Internacional.",
    benefits: ["Compatible con fertirriego", "Múltiples biostimulantes", "Ácidos húmicos y fúlvicos", "Doble Premio de Innovación"],
    application: "Aplicar vía fertirriego. Dosis: 1-2 kg/ha. Puede aplicarse en semillero y trasplante.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/glumix-irrigation.png",
  },
  {
    id: "13",
    name: "AZSeed",
    slug: "azseed",
    presentation: "Polvo humectable 100g",
    type: "Polvo humectable — Inoculante",
    description: "Inoculante de semillas con bacterias fijadoras de nitrógeno para mejorar germinación y vigor inicial.",
    fullDescription: "AZSeed es un inoculante de semillas a base de Azospirillum brasilense, Azotobacter spp., Rhizobium spp. y Bacillus spp. Las bacterias fijadoras de nitrógeno mejoran la germinación, el vigor inicial y el desarrollo radicular, reduciendo la dependencia de fertilizantes nitrogenados. Registro RSCO-115/VI/19.",
    benefits: ["Fijación biológica de nitrógeno", "Mejor germinación y vigor", "Múltiples cepas bacterianas", "OMRI Listed"],
    application: "Aplicar directamente a las semillas antes de la siembra. Dosis: 100g por 50 kg de semilla.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/azseed-new.png",
  },
  {
    id: "14",
    name: "Amikrone 1L",
    slug: "amikrone-1l",
    presentation: "Líquido concentrado 1L",
    type: "Líquido — Fertilizante orgánico",
    description: "Fertilizante orgánico líquido a base de L-Aminoácidos libres para bioestimulación y nutrición vegetal.",
    fullDescription: "Amikrone es un fertilizante orgánico formulado con L-Aminoácidos libres de alta concentración (materia orgánica 90.73%). Contiene un perfil completo de aminoácidos esenciales y microelementos (Cu, Mn, Zn, Ca) que estimulan el metabolismo vegetal, mejoran la respuesta al estrés y aumentan rendimientos.",
    benefits: ["90.73% materia orgánica", "Perfil completo de L-Aminoácidos", "Microelementos incluidos", "Estimulación del metabolismo"],
    application: "Aplicar foliarmente o en fertirrigación. Dosis foliar: 1-2 mL/L. Fertirrigación: 3-5 L/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/amikrone.png",
  },
  {
    id: "15",
    name: "Amikrone 500mL",
    slug: "amikrone-500ml",
    presentation: "Líquido concentrado 500mL",
    type: "Líquido — Fertilizante orgánico",
    description: "Presentación de 500mL del fertilizante orgánico líquido a base de L-Aminoácidos libres.",
    fullDescription: "Amikrone 500mL es la presentación compacta del fertilizante orgánico L-Aminoácidos de Biokrone. Misma fórmula de alta concentración (materia orgánica 90.73%) con perfil completo de aminoácidos esenciales y microelementos. Ideal para productores con superficies menores o para prueba del producto.",
    benefits: ["Presentación económica 500mL", "Misma fórmula concentrada", "L-Aminoácidos de alta calidad", "Fácil dosificación"],
    application: "Aplicar foliarmente o en fertirrigación. Dosis foliar: 1-2 mL/L. Fertirrigación: 3-5 L/ha.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/amikrone-500ml.png",
  },
  {
    id: "16",
    name: "BioElicitor",
    slug: "bioelicitor",
    presentation: "Líquido concentrado 1L",
    type: "Líquido — Fertilizante orgánico",
    description: "Fertilizante orgánico a base de extracto de algas marinas (Ascophyllum nodosum) con citocininas y citoquininas.",
    fullDescription: "BioElicitor es un fertilizante orgánico líquido formulado con extracto de algas Ascophyllum nodosum, rico en citocininas naturales, ácidos orgánicos y microelementos. Activa los mecanismos de defensa de la planta, mejora el cuajado de frutos y aumenta la tolerancia al estrés abiótico. Hecho en Irlanda.",
    benefits: ["Extracto de Ascophyllum nodosum", "Citocininas naturales", "Mejora cuajado y calidad de fruto", "Activador de defensas vegetales"],
    application: "Aplicar foliarmente en etapas clave. Dosis: 1-2 L/ha cada 10-15 días.",
    category: "BIOFORTIFICANTES",
    image: "/images/products/bio-elicitor.png",
  },
]

export const productCategories = [
  { value: "all", label: "Todos los productos" },
  { value: "FUNGICIDAS", label: "Fungicidas" },
  { value: "BIOINSECTICIDAS", label: "Bioinsecticidas" },
  { value: "BIOFORTIFICANTES", label: "Biofortificantes" },
]

export type ProductCategory = "all" | "FUNGICIDAS" | "BIOINSECTICIDAS" | "BIOFORTIFICANTES"

export function getProductBySlug(slug: string) {
  return productsData.find((p) => p.slug === slug)
}

export function getProductById(id: string) {
  return productsData.find((p) => p.id === id)
}
